### ISSUE TITLE
Enabling bluetooth problem

### ISSUE THREAD

**Issue by gmiragliotta** [gmiragliotta/SmartEnvironments#11]
If bluetooth is off, we have to ask the user to enable it via a new Activity (which destroy the current one). 
In this case i think it's better to resume the previous activity capturing the user input (ok / cancel). 
Even if the answer was "cancel" we must resume the previous activity, because the user could not understand what's going on.

**Comment by gmiragliotta** [comment]
Useful links:
https://stackoverflow.com/questions/18116666/bluetoothadapter-action-request-enable-calls-onactivityresult-immediately

**Comment by gmiragliotta** [comment]
Trying adding FLAG_ACTIVITY_NEW_TASK to intent flag

**Comment by khaelys** [comment]
The problem was a finish() call in the CameraActivity.
