### ISSUE TITLE
Train some neural network on specific smart objects

### ISSUE THREAD

**Issue by flongo82** [gmiragliotta/SmartEnvironments#4]
Let's identify some specific smart objects we want to activate and train the mobilenet neural network to recognize them.

**Comment by gmiragliotta** [comment]
No, it recognize only the new object

**Comment by gmiragliotta** [comment]
It seams training on a inception5h model instead of inception_v3 is more difficult.

**Comment by gmiragliotta** [comment]
Tried retraining successfully mobilenet neural network. I used the bigger mobile net, with a final size of 16Mb. 

https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html

Parameter to adjust:
INPUT_SIZE = 224
IMAGE_MEAN = 128;
IMAGE_STD = 128.0f;
INPUT_NAME = "input";
OUTPUT_NAME = "final_result";
