### ISSUE TITLE
Investigate technologies for voice recognition

### ISSUE THREAD

**Issue by flongo82** [gmiragliotta/SmartEnvironments#5]
Let's investigate technologies that can be used for voice recognition. The goal is to recognize simple commands like "switch on", "switch off" and similar. We probably need a neural network technology to perform speech to text and some other technology for comparing the recognized text with some predefined set of commands. Each smart object should have its own set of commands.

**Comment by gmiragliotta** [comment]
Useful resources:
https://github.com/gotev/android-speech
